version: "3.9"
services:
  rstudio:
    build: .
    ports:
      - "8787:8787"
    environment:
      PASSWORD: password
      DISABLE_AUTH: true
    volumes:
      - rstudio_data:/home/rstudio/workspace
      - ./.rstudio_config:/home/rstudio/.config/rstudio

volumes:
  rstudio_data: